### ISSUE TITLE
Inception do projeto verse

### ISSUE THREAD

**Issue by eoSalinas** [eoSalinas/verse#1]
# Um versículo a cada 24 horas

Olá a todos,

Estou iniciando um novo projeto open source chamado **Verse** e gostaria de compartilhar com vocês o propósito e a motivação por trás dele.

O **Verse** é uma aplicação simples que oferece um novo versículo bíblico a cada 24 horas. Ele visa ser uma fonte diária de inspiração e reflexão, compartilhando a sabedoria da palavra de Deus com o mundo!

![verse-thumb-2](https://github.com/eoSalinas/verse/assets/80262440/2e777a03-3658-4ea0-a584-debbf87a419a)

## O que buscamos construir juntos?

Além de levar uma mensagem que pode mudar o dia de uma pessoa, uma das razões para a construção dessa aplicação é abrir oportunidades para que as pessoas façam suas primeiras contribuições em projetos reais da comunidade.

Muitas vezes, podemos acreditar que contribuir para algo exige a realização de tarefas extremamente complexas. No entanto, este projeto visa desafiar esse pensamento e servir como um ponto de partida acessível para quem deseja começar a contribuir.

## Deixe sua marca neste projeto!

Para começarmos com o pé direito e impulsionarmos o projeto desde já! Deixe um 'oi' ou compartilhe o que você espera deste projeto nos comentários. Assim você já está começando a deixar sua marca no **Verse**!

Estamos abertos a todas as sugestões e ideias. Se você tem algo em mente, fique à vontade para comentar aqui.

**Comment by jhrick** [comment]
Bem, aqui vai minha contribuição:

Esse projeto pode ser um auxílio para mim, já que, neste exato momento eu me encontro perdido e também busco códigos open-source, codar com a comunidade.

Faz um tempinho que eu não mexo com JS ou TS, tenho focado bastante apenas em C para pegar uma boa base e continuar em outra linguagem de alto nível. Então, a partir disto, eu poderia desenvolver um CLI (**C**ommand-**L**ine **I**nterface) do projeto, me disponho a isso.

Se gostar da ideia e quiser levar ela pra frente, me manda mensagem no discord: `rick.369`, ou manda algum meio de contato para nos comunicarmos.

**Comment by GabrielLicar** [comment]
Que projeto interessante! Eu desenvolvi uma API da Bíblia usando Node.js e criei uma “rota” que retorna um versículo diferente a cada nova requisição. Achei muito legal o projeto, parabéns pela iniciativa. ❤️‍🔥🔥

Edit: repo do [projeto](https://git.new/biblia)

**Comment by joaovictornsv** [comment]
Parabéns pela iniciativa, de fato é um ótimo projeto e creio que será relevante tanto para os usuários quanto para os devs que irão contribuir.

Já tive uma ideia semelhante ao Verse, mas nunca tirei do papel 😅. Mas que bom que alguém já deu o pontapé inicial.

Tenho interesse em contribuir para esse projeto, tanto com código quanto com ideias. Aqui vão algumas:

- Suporte para diferentes versões da Bíblia
- Uma nova página dedicada a exibir um trecho de um livro cristão por dia.

Se quiser entrar em contato, meu discord é `joaovictornsv`.

**Comment by eoSalinas** [comment]
> Que projeto interessante! Eu desenvolvi uma API da Bíblia usando Node.js e criei uma “rota” que retorna um versículo diferente a cada nova requisição. Achei muito legal o projeto, parabéns pela iniciativa. ❤️‍🔥🔥
> 
> Edit: repo do [projeto](https://git.new/biblia)

@GabrielLicar muito irado! Eu acabei de dar uma olhada no seu repo, e achei super interessante a implementação da rota `/random`. 

Parabéns pelo projeto, excelente!

**Comment by eoSalinas** [comment]
> Bem, aqui vai minha contribuição:
> 
> Esse projeto pode ser um auxílio para mim, já que, neste exato momento eu me encontro perdido e também busco códigos open-source, codar com a comunidade.
> 
> Faz um tempinho que eu não mexo com JS ou TS, tenho focado bastante apenas em C para pegar uma boa base e continuar em outra linguagem de alto nível. Então, a partir disto, eu poderia desenvolver um CLI (**C**ommand-**L**ine **I**nterface) do projeto, me disponho a isso.
> 
> Se gostar da ideia e quiser levar ela pra frente, me manda mensagem no discord: `rick.369`, ou manda algum meio de contato para nos comunicarmos.

@jhrick fico extremamente feliz em saber que esse projeto pode te ajudar e que você escolheu esse projeto aqui para codar com a comunidade como você mesmo disse.

Eu acho incrível a ideia da **CLI**, e todas as contribuições são bem vindas!

Partindo disso, como você propõe o desenvolvimento? E o que você espera dessa CLI?

Sendo sincero **eu curti a ideia**, e acho que poderia ser feito! 😁

**Comment by eoSalinas** [comment]
> Parabéns pela iniciativa, de fato é um ótimo projeto e creio que será relevante tanto para os usuários quanto para os devs que irão contribuir.
> 
> Já tive uma ideia semelhante ao Verse, mas nunca tirei do papel 😅. Mas que bom que alguém já deu o pontapé inicial.
> 
> Tenho interesse em contribuir para esse projeto, tanto com código quanto com ideias. Aqui vão algumas:
> 
>     * Suporte para diferentes versões da Bíblia
> 
>     * Uma nova página dedicada a exibir um trecho de um livro cristão por dia.
> 
> 
> Se quiser entrar em contato, meu discord é `joaovictornsv`.

Muito massa as ideias @joaovictornsv!

Fico absurdamente feliz ao saber do seu interesse em contribuir com esse projeto.
Inclusive o **Suporte para diferentes versões da Bíblia** poderia ser um simples combobox no card do versículo... é de se pensar! 🤔

**Comment by jhrick** [comment]
> @jhrick fico extremamente feliz em saber que esse projeto pode te ajudar e que você escolheu esse projeto aqui para codar com a comunidade como você mesmo disse.
> 
> Eu acho incrível a ideia da **CLI**, e todas as contribuições são bem vindas!
> 
> Partindo disso, como você propõe o desenvolvimento? E o que você espera dessa CLI?
> 
> Sendo sincero **eu curti a ideia**, e acho que poderia ser feito! 😁

Como tinha falado, atualmente eu estou estudando **C**, então eu poderia começar a construção usando esta linguagem. Mas nada impede de usar outras linguagens como **Python**, **Js**, **Go**, a que for melhor - seja por questão de portabilidade ou outros motivos -, eu me disponho a isso.

A ideia é que a CLI faça uma requisição para uma API, obtendo assim o versículo. Toda vez que o terminal fosse aberto o versículo apareceria, podendo até ficar como uma **mensagem fixada** - se for do interesse do usuário.

**Comment by LuanAnalistadeTI** [comment]
Opa! Show de bola! Glórias a DEUS por isso! A paz do SENHOR! 
Como posso contribuir? Sou Analista de TI e UX/UI Designer 
Como posso ajudar com design? Precisar, só falar comigo! 
Meu contato: https://linktr.ee/luandesignerfreelancer

**Comment by clovisdanielss** [comment]
Legal. Acredito que pode ser edificante. 
Sabe, existem várias aplicações que tem essa ideia de trazer um verso por dia. Mas que tal fazer uma forma de incentivo (gameficação) para incentivar a pessoa a decorar o verso daquele dia ? 

Aí é pensar na regra, mas algo tipo se a pessoa acertar verso do dia anterior ganhar pontos ? (Pode ser também acertar % de palavras por meio de tokenização)

Enfim. Achei legal a ideia, vou seguir por aqui. Quem sabe acabo contribuindo. 

Não sei se o que você quer seria um brainstorming com a galera, ou não, eu entendi isso por isso estou estendendo o escopo da ideia, porém tentando centralizar no 1 verso por dia.

**Comment by eoSalinas** [comment]
> > @jhrick fico extremamente feliz em saber que esse projeto pode te ajudar e que você escolheu esse projeto aqui para codar com a comunidade como você mesmo disse.
> > Eu acho incrível a ideia da **CLI**, e todas as contribuições são bem vindas!
> > Partindo disso, como você propõe o desenvolvimento? E o que você espera dessa CLI?
> > Sendo sincero **eu curti a ideia**, e acho que poderia ser feito! 😁
> 
> Como tinha falado, atualmente eu estou estudando **C**, então eu poderia começar a construção usando esta linguagem. Mas nada impede de usar outras linguagens como **Python**, **Js**, **Go**, a que for melhor - seja por questão de portabilidade ou outros motivos -, eu me disponho a isso.
> 
> A ideia é que a CLI faça uma requisição para uma API, obtendo assim o versículo. Toda vez que o terminal fosse aberto o versículo apareceria, podendo até ficar como uma **mensagem fixada** - se for do interesse do usuário.

@jhrick acho que seria super interessante termos uma **CLI**! Caso você queira realizar essa empreitada fique a vontade, será valioso para o projeto!

O único ponto é que vamos ajustar algumas coisas em breve a respeito da API e como ela seleciona os versículos, mas acredito que não será um problema. Caso queria saber mais, veja a issue #2 

Vou te adicionar no discord, qualquer podemos conversar por lá!

**Comment by eoSalinas** [comment]
> Opa! Show de bola! Glórias a DEUS por isso! A paz do SENHOR! Como posso contribuir? Sou Analista de TI e UX/UI Designer Como posso ajudar com design? Precisar, só falar comigo! Meu contato: https://linktr.ee/luandesignerfreelancer

@LuanDesigner era você que eu estava esperando! 😂 

Seja bem vindo, a paz, tudo bem?

Atualmente, nosso projeto não possuí uma "identidade visual reconhecível". No entanto isso virá com o tempo!
Inicialmente precisamos apenas de um **icon**, para ser usado no **favicon** e arquivo de **manifesto**.

Posso abrir uma issue para discutirmos isso?

**Comment by eoSalinas** [comment]
> Legal. Acredito que pode ser edificante. Sabe, existem várias aplicações que tem essa ideia de trazer um verso por dia. Mas que tal fazer uma forma de incentivo (gameficação) para incentivar a pessoa a decorar o verso daquele dia ?
> 
> Aí é pensar na regra, mas algo tipo se a pessoa acertar verso do dia anterior ganhar pontos ? (Pode ser também acertar % de palavras por meio de tokenização)
> 
> Enfim. Achei legal a ideia, vou seguir por aqui. Quem sabe acabo contribuindo.
> 
> Não sei se o que você quer seria um brainstorming com a galera, ou não, eu entendi isso por isso estou estendendo o escopo da ideia, porém tentando centralizar no 1 verso por dia.

@clovisdanielss é exatamente isso, perspectivas diferentes para esse projeto (como um brainstorm)!

Achei incrível sua ideia de gameficar a aplicação, isso pode trazer um grande diferencial e **engajar as pessoas com a palavra de Deus!**

**Comment by eoSalinas** [comment]
Quero expressar minha **sincera gratidão** a todos que contribuíram para esta issue. Graças às discussões realizadas, **obtivemos insights valiosos** que certamente impulsionarão a evolução do projeto. 

**É inegável o impacto que cada um de vocês está deixando nesta jornada**. Estou ansioso para trabalharmos juntos novamente. Obrigado mais uma vez por abraçarem a ideia, **glória a Deus!**

**Comment by LuanAnalistadeTI** [comment]
> > Opa! Show de bola! Glórias a DEUS por isso! A paz do SENHOR! Como posso contribuir? Sou Analista de TI e UX/UI Designer Como posso ajudar com design? Precisar, só falar comigo! Meu contato: https://linktr.ee/luandesignerfreelancer
> 
> @LuanDesigner era você que eu estava esperando! 😂
> 
> Seja bem vindo, a paz, tudo bem?
> 
> Atualmente, nosso projeto não possuí uma "identidade visual reconhecível". No entanto isso virá com o tempo! Inicialmente precisamos apenas de um **icon**, para ser usado no **favicon** e arquivo de **manifesto**.
> 
> Posso abrir uma issue para discutirmos isso?

Cara, que vergonha!! kkkkkkk... Só agora pude te responder... Muita correria... Mas é isso.
Estou bem, e você? Pode sim abrir... Fala comigo!!! @eoSalinas

**Comment by LuanAnalistadeTI** [comment]
@eoSalinas Qualquer coisa fala comigo usando meus contatos --> https://linktr.ee/luandesignerfreelancer 
(eu demorei demais pra te responder aqui...) Valeu! : )

**Comment by LuanAnalistadeTI** [comment]
@eoSalinas Cara, já tem 2 dias que o versículo passa de 24h e não muda, acho que está dando algo errado... Desde ontem que o horário está em loop, passa 24h e ele continua contando sem mudar... Está parado em (Atos 19:20)

**Comment by eoSalinas** [comment]
Tranquilo @LuanDesigner, acontece kkkkkkk

Então sobre o versículo não trocar, deve ter dado algun bugzin, então eu mandei um redeploy e resolveu, pode ter sido algo no cron job ou cache... mas agora está funcionando! Valeu pelo toque.

**Comment by LuanAnalistadeTI** [comment]
Pronto! @eoSalinas provavelmente pode ter sido cron job, já que você fez a redeploy (deu reset) kkkkkk...
Beleza, tamo junto! Qualquer coisa, só falar... Valeu!
