### ISSUE TITLE
Tema claro e escuro

### ISSUE THREAD

**Issue by hiroshimorowaka** [eoSalinas/verse#14]
Seria uma boa ideia adicionar um **modo claro e escuro**. 

Eu tenho bastante dificuldade pra ler em modo claro e isso me incômoda bastante, além de que seria uma boa ferramenta de acessibilidade também. 

Eu posso abrir um PR implementando essa ideia se concordarem com a ideia.

**Comment by eoSalinas** [comment]
@hiroshimorowaka **concordo totalmente com a ideia do dark mode!** Eu só não vou falar para você lançar essa PR agora, porque será trabalho em vão... Vou te explicar!

Acabei de abrir a issue #15 para discutir um **redesign no projeto**! Acho que seria interessante começarmos por lá inclusive te faço o convite para levar sua sugestão de **modo claro e escuro** para essa nova issue, assim podemos juntar todas as ideias!  O que você acha?
