### ISSUE TITLE
Design e Identidade Visual para o Verse

### ISSUE THREAD

**Issue by eoSalinas** [eoSalinas/verse#15]
**Sabemos que, para o Verse evoluir, precisamo de uma marca mais definida.**

Desde o início do projeto, o design é simples mas funcional - sinceramente não me preocupei muito com o estético - porém necessita de uma identidade. 

E como Deus é perfeito, no momento exato apareceu nosso amigo [eliezercastro](https://www.tabnews.com.br/eliezercastro) que criou um design incrível e compartilhou comigo em uma [postagem no TabNews](https://www.tabnews.com.br/eliezercastro/356966a5-78b5-4dbe-afe8-ed5cafe4af7c).

Se liga no design:

![redesign-verse](https://github.com/eoSalinas/verse/assets/80262440/62853776-9cc9-455a-a161-f988fc277baf)

**Eu achei SENSACIONAL!** Se quiser conferir em mais detalhes, aqui está o link do [projeto no Figma](https://www.figma.com/file/g6rdzv8IxRZss0jzgArMUj/Verse?type=design&node-id=0%3A1&mode=design&t=GEVxLuBunQbb9wlg-1).

Abri esta issue para discutirmos sobre o design, o logotipo e qualquer aspecto estético relacionado ao projeto.

Tem alguma ideia para melhorar esse design? Ou talvez tenha outra sugestão? Fique à vontade para comentar, **todas as contribuições são bem-vindas!**

Quanto mais opiniões, melhor! Vamos dar ao Verse uma nova identidade.

**Comment by hiroshimorowaka** [comment]
Eu achei sensacional também, principalmente as novas funcionalidades de ver o versículo completo, detalhes sobre o autor etc. O projeto com toda certeza vai ficar muito lindo e com uma cara única, exclusiva do Verse. 

Sobre o modo claro e escuro, eu tava pensando em algo assim:

![theme](https://github.com/eoSalinas/verse/assets/82670390/c4ace618-e8e6-4a72-a1e4-015270e7afb1)

Não sou muito bom com cores, mas tentei meu melhor. Aceito sugestões
 
O botão de tema é um Dropdown que tem as opções:
- Light (claro)
- Dark (escuro)
- System (Corresponder ao navegador)

Eu tava pensando em deixar ele sem fundo, só com uma bordinha, mas não sei se irá ficar legal visualmente falando.

**Comment by eliezer-castro** [comment]
Gostaria de expressar minha gratidão pela oportunidade de contribuir com o projeto Verse. Fico imensamente feliz em saber que o design que compartilhei foi bem recebido e estou animado para continuar colaborando no desenvolvimento da identidade visual do Verse (Apesar de não ser a minha especialidade 😅). 

Estou totalmente aberto a qualquer sugestão ou feedback adicional sobre o design apresentado.

**Comment by hiroshimorowaka** [comment]
> Estou totalmente aberto a qualquer sugestão ou feedback adicional sobre o design apresentado.

@eliezer-castro seu design ficou **MUITO** bom, inclusive se tiver algum crítica ao meu tema escuro apresentado, fique a vontade. 
Design não é o meu forte kkkk

**Comment by eliezer-castro** [comment]
Padronizei o layout na versão clara e adicionei uma variante V2 no Figma implementando o modo escuro. Para visualizar o resultado final, basta acessar o projeto no [figma](https://www.figma.com/file/g6rdzv8IxRZss0jzgArMUj/Verse?type=design&node-id=115%3A2&mode=design&t=scf8pQVkaIv3NeVv-1)

Estou totalmente aberto a qualquer sugestão ou feedback adicional sobre o design apresentado.



<img width="1440" alt="preview" src="https://github.com/eoSalinas/verse/assets/27421027/f896d523-3abf-43b7-b6b4-339224bb74b3">

**Comment by eliezer-castro** [comment]
Padronizei o layout na versão clara e adicionei uma variante V2 no Figma implementando o modo escuro. Para visualizar o resultado final, basta acessar o projeto no [figma](https://www.figma.com/file/g6rdzv8IxRZss0jzgArMUj/Verse?type=design&node-id=115%3A2&mode=design&t=scf8pQVkaIv3NeVv-1)

Estou totalmente aberto a qualquer sugestão ou feedback adicional sobre o design apresentado.

![preview](https://github.com/eoSalinas/verse/assets/27421027/4095679e-8193-400b-96a7-bb77ed007e1b)

**Comment by hiroshimorowaka** [comment]
> Padronizei o layout na versão clara e adicionei uma variante V2 no Figma implementando o modo escuro. Para visualizar o resultado final [...]
> Estou totalmente aberto a qualquer sugestão ou feedback adicional sobre o design apresentado.

Ficou muito bom @eliezer-castro!. Achei bem simples de entender e utilizar, mas ao mesmo tempo bem bonito. Também gostei bastante do background na versão em modo escuro, ajuda a visualizar melhor o conteúdo.

**Comment by johanvilela** [comment]
### O novo design ficou sensacional 👏

Parabéns, galera!

@eliezer-castro Se eu puder deixar aqui a minha sugestão é a seguinte: Aumentar um pouquinho o contraste entre o `card` e o `fundo` no modo escuro. Teria que testar um tom escuro, só que um pouquinho mais claro no fundo para dar mais destaque ao card.

Sei que é um detalhe, mas acredito que são os detalhes que trazem a beleza para o design.

**Comment by B-Schmitz** [comment]
Essa última imagem está melhor, tema light e dark clássico preto e branco, nada de fundo amarelo, só coloca um contraste muito bom nas duas versões e ok

Checa aqui: [Contrast-checker](https://coolors.co/contrast-checker/112a46-acc8e5)

**Comment by eliezer-castro** [comment]
Modifiquei a cor de fundo do modo claro para o branco padrão do tema Zinc do shadcn/ui. Busquei manter a fidelidade ao estilo do shadcn/ui.

**Comment by eoSalinas** [comment]
Incrível!

A sugestão de implementar o dark mode do @hiroshimorowaka veio no momento exato e se encaixou perfeitamente à adaptação proposta pelo @eliezer-castro. A propósito a v2 ficou irada!

**Essas novas features vão agregar muito valor ao projeto.**

Neste momento do Verse, sugiro realizarmos uma abordagem mais incremental. Ao invés de implementarmos todas as novas funcionalidades de uma vez, poderíamos concentrar nossos esforços na implementação do novo layout, inicialmente, focando no "core" e mantendo a aplicação mais simples. Dessa forma, poderemos já apresentar uma nova aparência para o **Verse** e, ao mesmo tempo, começar a planejar alcançar mais usuários.

Conforme essa etapa for se estabilizando, podemos ir adicionando as novas funcionalidades. O que vocês acham?

**Comment by eoSalinas** [comment]
Aproveitando o momento @eliezer-castro, gostaria de levantar uma outra ideia...
O que vocês acham de uma **página dos contribuidores**?

Seria uma forma especial de reconhecer e agradecer a todos que contribuíram com o projeto, seja de forma direta ou indireta, adicionando código, versículos, ou ajudando de alguma maneira!

**Comment by eoSalinas** [comment]
O @GersonRocha9 trouxe uma ideia bem interessante! **Permitir o usuário compartilhar o versículo.**

**Comment by GersonRocha9** [comment]
Isso, pensei em uma feature onde tivéssemos um botão para exportar o PNG do versículo para as redes sociais direto.

**Comment by eliezer-castro** [comment]
Absolutamente @eoSalinas! Estou totalmente de acordo com a ideia da página de contribuidores. É uma maneira incrível de reconhecermos e expressarmos nossa gratidão a todos que ajudaram. Estou empolgado em trabalhar nisso.

@GersonRocha9, recentemente adicionei um ícone de download ao design para possibilitar a exportação da imagem do versículo. No entanto, reconheço que a funcionalidade pode não estar tão clara ou intuitiva quanto gostaríamos. Você tem alguma sugestão sobre como poderíamos melhorá-la? Estou aberto a ideias e feedback para garantir que essa funcionalidade seja fácil de usar e compreender para todos os usuários.

Outrossim, adorei a sugestão de permitir que o usuário compartilhe o versículo e já a integrei ao design para validação. Abaixo, compartilho um preview de como ficou

![share](https://github.com/eoSalinas/verse/assets/27421027/7f5c083b-c8a8-44ce-a92b-1ee2dbb3af10)

Para visualizar o resultado final, basta acessar o projeto no [Figma](https://www.figma.com/file/g6rdzv8IxRZss0jzgArMUj/Verse?type=design&node-id=115%3A2&mode=design&t=scf8pQVkaIv3NeVv-1)

Estou totalmente aberto a qualquer sugestão ou feedback adicional sobre o design.

**Comment by GersonRocha9** [comment]
@eliezer-castro Achei que ficou ótimo essa opção de compartilhamento. Sobre o botão de download, ele já faria o export do PNG do versículo direto? 

@eoSalinas  pretende fazer uma versão para app mobile para as lojas? Daria pra fazer notificações locais lembrando o usuário de ver a cada vez que for disponibilizado um novo versículo.

**Comment by eliezer-castro** [comment]
@GersonRocha9 Isso mesmo! 🫡

@eoSalinas Acredito que criar uma seção de "Contribuidores" no Drawer de Sobre é uma ótima maneira de reconhecer e agradecer a todos que ajudaram o projeto. Essa seção inclui uma lista de todos os colaboradores, com seus nomes e links para seus perfis (se disponíveis).

Gostaria de saber o que você acha da solução que implementei. Caso tenha outras ideias ou sugestões, por favor, compartilhe comigo!

Abaixo, compartilho um preview de como ficou. 
![Compartilhar](https://github.com/eoSalinas/verse/assets/27421027/fbdb1f31-3c23-4e75-943f-8c6bae4b56ad)

**Comment by B-Schmitz** [comment]
Nas divisões de contribuições eu colocaria apenas ao centro a palavra contribuidores, e o avatar de cada um abaixo, somente daqueles que fizeram commits no projeto, talvez usando a api do github consiga já saber quais são os contribuidores e assim atualizar automaticamente.

**Comment by hiroshimorowaka** [comment]
> Gostaria de saber o que você acha da solução que implementei. Caso tenha outras ideias ou sugestões, por favor, compartilhe comigo!

Concordo com o @B-Schmitz , ficaria interessante se deixasse só um título "Contribuidores" e puxasse o perfil direto da API do Github. 

Mas em questão de aparência, eu achei que ficou muito bom.

**Comment by eoSalinas** [comment]
> @eoSalinas pretende fazer uma versão para app mobile para as lojas? Daria pra fazer notificações locais lembrando o usuário de ver a cada vez que for disponibilizado um novo versículo.

Boaa @GersonRocha9! Penso sim em fazer uma versão mobile, só não sei quando :joy:
Inclusive sua ideia das notificações de alerta é bem legal.

Acredito que uma versão mobile para o **Verse** faça mais sentido conforme o projeto for amadurecendo.

**Comment by eoSalinas** [comment]
> Gostaria de saber o que você acha da solução que implementei. Caso tenha outras ideias ou sugestões, por favor, compartilhe comigo!
> 

@eliezer-castro gostei muito do conceito dos contribuidores no Drawer de Sobre, é uma excelente lugar ao meu ver!

De fato colocar o texto **contribuidores** ao centro, como o @B-Schmitz disse, pode traz um destaque maior aos contribuidores e isso é bom. (Para validar e saber onde ficará melhor, precismos testar no layout)

Além disto, tem um ponto que gostaria de levantar, **acredito que todos os contribuidores devem estar em pé de igualdade**. E isso é um ponto delicado, porque pensem comigo, se utilizarmos somente a **API do GitHub**, apenas quem fez commit ira contar...

No entanto, existe muitas contribuições valiosas como essa aqui do @eliezer-castro, que não necessáriamente está em um commit!

Minha sugestão seria mesclar as ideias do @eliezer-castro e do @B-Schmitz, ao invés de contribuidores em destaque, deixamos todos os contribuidores que realizaram commits. E abaixo agradecimentos especiais, o que pode incluir contribuições fora do escopo de commits.

Outra coisa, talvez nem precise da role de equipe principal, **equipe principal é todos que contribuem** :muscle: :joy:

Galera tudo o que eu disse aqui são opniões, ideias e perspectivas minhas, se você acha que algo não faz sentido ou tem um contra ponto, por favor fique a vontade para debatermos e conversarmos, somente dessa forma atingiremos um excelente resultado.

**Comment by johanvilela** [comment]
> Minha sugestão seria mesclar as ideias do @eliezer-castro e do @B-Schmitz, ao invés de contribuidores em destaque, deixamos todos os contribuidores que realizaram commits. E abaixo agradecimentos especiais, o que pode incluir contribuições fora do escopo de commits.

Achei essa ideia muito boa! Vai facilitar bastante a organização dessa seção.

**Comment by clovisdanielss** [comment]
Ô galera, acho que estamos fugindo do escopo dessa issue, não ? 

Melhor abrir outra ou fechar caso já tenha sido tudo decidido.

**Comment by eoSalinas** [comment]
> Ô galera, acho que estamos fugindo do escopo dessa issue, não ?

De fato acabamos nos afastanto um pouco do escopo da issue :joy:, mas olhando o lado bom, sugiram novas ideias para o **Verse**!

Como já tem alguns dias desde a última interação aqui, seguirei o conselho do @clovisdanielss de fechar a issue. Em breve trarei novidades para começarmos a trilhar nesse novo caminho.

**Gostaria de expressar minha gratidão a todos que participaram desta discussão**, compartilhando suas ideias e ajudando. Sem dúvidas o Verse fecha essa issue com novas perspectivas!

Obrigado @B-Schmitz , @johanvilela, @clovisdanielss, @GersonRocha9, @hiroshimorowaka.

Em especial gostaria de agradecer o @eliezer-castro, por trazer um novo conceito para o **Verse**.

**Romanos 11:36**
