### ISSUE TITLE
Opção de compartilhamento no WhatsApp

### ISSUE THREAD

**Issue by GersonRocha9** [eoSalinas/verse#22]
Eu tenho uma sugestão que é de alguma forma, ter um botão para exportar o container do versículo como um print. O app Glorify faz algo semelhante e eu conheço várias pessoas que gostam de compartilhar as mensagens de forma rápida. Ter a opção de abrir o site, clicar num botão e já ter a imagem pronta para compartilhar no WhatsApp com alguém é uma feature muito útil.

**Comment by eoSalinas** [comment]
@GersonRocha9 essa feature que você sugeriu é bem interessante mesmo! Inclusive quero muito trazê-la para o projeto :joy: 

> eu conheço várias pessoas que gostam de compartilhar as mensagens de forma rápida.

Isso pode trazer facilidade, além de espalhar a palavra e contribuir para o crescimento.

Na issue #15, estamos trabalhando em uma nova UI para o **Verse**, e provavelmente lá é o melhor lugar para começarmos a "mapear" essa feature. 

**Agradeço de coração pela sua sugestão e dica!**

PS. Dá uma passada lá na issue, você será mais que bem vindo! Quanto mais ideias para o layout melhor. :smile:
