### ISSUE TITLE
Adicionar um `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by hiroshimorowaka** [eoSalinas/verse#25]
### Sugestão

Acho que seria interessante adicionar `CONTRIBUTING.md` na raiz do projeto e linkar ele no Readme principal.
 
Nesse arquivo ficaria um "tutorial" de como contribuir com o projeto, seja apenas adicionando versículos ou com código mesmo. 

Fica mais fácil de contribuir e consequentemente pode atrair mais pessoas, mesmo as que nunca tiveram a primeira experiência com Open Source. 

Além de ajudar pessoas mais desatentes (como eu) a não abrir PR na `main` (exatamente oq eu fiz), explicar que é pra abrir na `develop`.

**Comment by eoSalinas** [comment]
Boaa ideia @hiroshimorowaka! Isso pode facilitar bastante o entendimento de como contribuir, vou providênciar. :smile: :handshake:

**Comment by eoSalinas** [comment]
Opa, passando aqui para avisar que acabei de adicionar o `CONTRIBUTING.md` conforme você sugeriu @hiroshimorowaka. Valeu!
