### ISSUE TITLE
[BUG] countdown com valor incorreto

### ISSUE THREAD

**Issue by B-Schmitz** [eoSalinas/verse#29]
![bug](https://github.com/eoSalinas/verse/assets/26826885/0dee883c-dcf9-4392-bfa3-6ebd57aa3aa6)
 
Ali deveria mostrar 21:59:56, mas os minutos vem 60

**Comment by eoSalinas** [comment]
Opa, tudo bem @B-Schmitz? Verdade, deveria!

Esse bug foi [corrigido aqui](https://github.com/eoSalinas/verse/pull/18/commits/34267344de53efc33414ec7bde9909c3967a32b0#diff-b81b9a4b34decdf321dc131b2338aa9b0047cfd99a54895664467ed004d50949) pelo @hiroshimorowaka, porém ainda está na branch develop. Obrigado por avisar.
