### ISSUE TITLE
Pré-selecionando 365 versículos

### ISSUE THREAD

**Issue by eoSalinas** [eoSalinas/verse#5]
## Metas de versículos 🎯
- [x] 1 versículo adicionado;
- [x] 10 versículos adicionados;
- [x] 50 versículos adicionados;
- [x] 100 versículos adicionados;
- [x] 🥉 200 versículos adicionados;
- [x] 🥈 300 versículos adicionados;
- [x] 🥇 365 versículos adicionados; 

---

Nem sempre toda contribuição em um projeto da comunidade precisa ser extremamente complexa, na verdade ela precisa apenas **agregar valor!**

Dito isso, **precisamos criar uma lista de 365 versículos pré-selecionados!**
Sim, poderíamos fazer um web scrapping, pedir ao GPT, ou utilizar qualquer outra estratégia. Mas, o que poderia ser mais gratificante e único do que a contribuição direta dos membros da comunidade?

Por este motivo, [escolhemos utilizar um simples **arquivo JSON** com **referências a versículos**](https://github.com/eoSalinas/verse/issues/2#issuecomment-2016654504) que você pode ajudar a selecionar! Além disso esse será o repertório de possíveis versículos a impactar os usuários do **Verse**.

> Cada versículo que você adiciona não apenas enriquece a aplicação, mas também pode inspirar e atingir positivamente os usuários.

## Como você pode contribuir?

Atualmente temos uma branch chamada `feat/add-365-verses`.

É nesta branch que vamos concentrar todas as contribuições de versículos, pelo menos os 365 iniciais para colocarmos em produção!

Para adicionar um versículo e fazer sua primeira contribuição, siga estes passos:

1. Faça um fork do projeto.
> O fork é uma cópia do projeto que você pode modificar conforme desejar, e depois pode sincronizar com as modificações das outras pessoas do repositório.
2. Clone o seu fork para sua máquina usando Git ou GitHub CLI.
3. Adicione os versículos na branch `feat/add-365-verses` do seu fork, através do arquivo **verses.json** localizado em `src/verses.json`.

![intellisense-books](https://github.com/eoSalinas/verse/assets/80262440/28aa6a80-fad8-4de8-aec8-38fed077bd41)

Por exemplo, se eu quero adicionar **Provérbios‬ ‭5‬:‭23**, ficaria desta maneira:

```json
{
	"abbrev": "pv",
	"chapter": "5",
	"verse": "23"
}
```

**abbrev**: abreviação do livro, temos uma [lista das abreviações aqui](https://github.com/eoSalinas/verse/issues/3) para ajudar;
**chapter**: capítulo do livro;
**number**: número do versículo;

4. Após adicionar o versículo, faça um commit.
Nesse projeto, estamos utilizando o [Conventional Commits](https://www.conventionalcommits.org/pt-br/v1.0.0/).
Exemplo de commit: `feat: add verse proverbios 5:23`

5. Quanto tiver terminado todas as suas contribuições, faça um pull request (PR) das modificações para a branch `feat/add-365-verses` do repositório oficial.

**Comment by johanvilela** [comment]
É preciso **desmarcar** a opção `Copy the main branch only` para ter o branch `feat/add-365-verses` no seu repositório

![fork](https://github.com/eoSalinas/verse/assets/30961343/2122fbdd-f3da-49bb-8968-377f60206b1c)

**Comment by eoSalinas** [comment]
Valeuu @johanvilela!

**Comment by johanvilela** [comment]
@eoSalinas Eu queria trocar uma ideia contigo, mas não encontrei o seu perfil no LinkedIn. Como poderia entrar em contato?

**Comment by eoSalinas** [comment]
> @eoSalinas Eu queria trocar uma ideia contigo, mas não encontrei o seu perfil no LinkedIn. Como poderia entrar em contato?

É pra já @johanvilela! Acabei de te deixar uma mensagem no LinkedIn, te aguardo lá. 🤝😁

**Comment by eoSalinas** [comment]
Obrigado a todos que contribuiram para concluir essa issue! Sem dúvidas os versículos que vocês selecionaram terão um grande impacto aos usuários do **Verse**.

Romanos 11:36
